/* sw.js — Leaf PWA Service Worker */

// Derive the base path from the SW's own URL so the app works
// correctly regardless of install path (e.g. /v6/spa/, /, /notes/).
// self.location.pathname = '/v6/spa/sw.js' → base = '/v6/spa'
const BASE = self.location.pathname.replace(/\/sw\.js$/, '');

// Namespace the cache so multiple instances on the same origin don't
// race on the same cache bucket.
const _slug = BASE.replace(/^\/|\/$/g, '').replace(/\//g, '-');
const CACHE = _slug ? `leaf-v6:${_slug}` : 'leaf-v6';

const SHELL = [
  `${BASE}/`,
  `${BASE}/index.html`,
  `${BASE}/css/layout.css`,
  `${BASE}/css/theme-dark.css`,
  `${BASE}/css/theme-light.css`,
  `${BASE}/css/theme-magenta.css`,
  `${BASE}/css/theme-paired-12.css`,
  `${BASE}/css/hljs.css`,
  `${BASE}/css/cm.css`,
  `${BASE}/css/katex.css`,
  `${BASE}/css/spreadsheet.css`,
  `${BASE}/app.js`,
  `${BASE}/manifest.json`,
  `${BASE}/icons/icon-192.svg`,
  `${BASE}/icons/icon-512.svg`,
];

// ── Install: pre-cache all app assets ───────────────────────────────────
self.addEventListener('install', e => {
  console.log("[SW] install event firing");
  e.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);

      // 1. Pre-cache static non-JS shell assets (CSS, icons, manifest)
      await cache.addAll(SHELL);

      // 2. Fetch the build manifest (generated by esbuild --metafile
      //    post-processing in package.json) and pre-cache all JS files.
      //    Done one-by-one so a single failure doesn't abort the batch.
      let jsCount = 0;
      try {
        const manifestResp = await fetch(`${BASE}/files-cache.json`);
        if (manifestResp.ok) {
          const fileNames = await manifestResp.json();
          for (const f of fileNames) {
            try {
              const resp = await fetch(`${BASE}/${f}`);
              if (resp.ok) {
                await cache.put(`${BASE}/${f}`, resp);
                jsCount++;
              }
            } catch (_) { /* skip individual failures */ }
          }
          console.log(`[SW] Pre-cached ${jsCount}/${fileNames.length} JS files from manifest`);
        }
      } catch (err) {
        console.warn('[SW] Manifest pre-cache failed (non-fatal):', err);
      }

      // Post install result to all clients so the page console can see it
      try {
        const clients = await self.clients.matchAll({ includeUncontrolled: true });
        for (const client of clients) {
          client.postMessage({ type: 'sw-installed', jsCount });
        }
      } catch (_) { /* ignore */ }

      await self.skipWaiting();
    })()
  );
});

// ── Activate: remove old caches ───────────────────────────────────────────
self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys.filter(k => k !== CACHE).map(k => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

// ── Fetch strategy ────────────────────────────────────────────────────────
self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);

  // Auth and spa-config calls → network only, no fallback.
  // Let network errors propagate so auth.ts can distinguish
  // "server unreachable" from "auth rejected", and config.ts
  // can fall back to its localStorage cache.
  if (url.pathname.includes('/api/') &&
      (url.pathname.includes('/auth') || url.pathname.includes('/spa-config'))) {
    e.respondWith(fetch(e.request));
    return;
  }

  // Other API calls (sync, history, trash, etc.) → network only,
  // never cached, offline fallback
  if (url.pathname.includes('/api/')) {
    e.respondWith(
      fetch(e.request).catch(() =>
        new Response(
          JSON.stringify({ error: 'Offline', changes: [], currentRevision: null }),
          { headers: { 'Content-Type': 'application/json' } }
        )
      )
    );
    return;
  }

  // Everything else → cache first, fall back to network, update cache.
  // If both cache and network fail, return a 503 so the browser can
  // surface a graceful error instead of an unhandled promise rejection
  // that crashes the JS module loader for code-split chunks.
  e.respondWith(
    caches.match(e.request).then(cached => {
      if (cached) return cached;
      return fetch(e.request).then(res => {
        if (e.request.method === 'GET' && res.status === 200) {
          const clone = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, clone));
        }
        return res;
      }).catch(() => {
        // Serve a minimal valid JS module for .js requests so Firefox
        // doesn't reject with NS_ERROR_CORRUPTED_CONTENT on MIME mismatch.
        const isJs = url.pathname.endsWith('.js');
        return new Response(
          isJs ? '/* offline — resource not cached */' : 'Offline — resource not cached',
          { status: 503,
            headers: { 'Content-Type': isJs ? 'application/javascript' : 'text/plain' } }
        );
      });
    })
  );
});

// ── Background sync hook (reserved for future use) ────────────────────────
self.addEventListener('sync', e => {
  if (e.tag === 'sync-notes') {
    console.log('[SW] Background sync triggered');
  }
});

// ── Message: allow the app to trigger immediate activation ───────────────
self.addEventListener('message', e => {
  if (e.data?.action === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
