/**
 * notes.ts — data access layer
 *
 * All reads/writes go to IndexedDB first.  The server is never called
 * directly from here.  Sync-queue entries are generated by sync.ts via
 * the change-bus, so notes.ts is purely persistence + publish.
 */

import {
  dbListNotes,
  dbGetNote,
  dbSaveNote,
  dbDeleteNote,
  dbCreateNote,
  dbRenameNote,
  dbFullTextSearch,
} from './db.js';
import { parseFrontmatter } from './frontmatter.js';
import type { FrontmatterResult } from './frontmatter.js';
import { applyAutotags } from './autotag.js';
import { publish } from './change-bus.js';
import { isSystemNote, getSystemNote } from './system-notes/registry.js';
export { isSystemNote };

/** Note metadata returned by listNotes(). */
export interface NoteMeta {
  id: string;
  created_at: number;
  updated_at: number;
  current: string;
}

/**
 * Full note data returned by loadNote().
 * Merges IndexedDB record fields with parsed frontmatter.
 */
export interface NoteData {
  id: string;           // note id (filename)
  content: string;      // full raw content (frontmatter + body)
  created_at: number;   // from IndexedDB record
  updated_at: number;   // from IndexedDB record
  current: string;      // from IndexedDB record
  created_by: string;   // from IndexedDB record (authoritative)
  updated_by: string;   // from IndexedDB record (authoritative)
  meta: FrontmatterResult['meta'];  // parsed frontmatter
}

/** Full-text search result — metadata + content snippet. */
export interface FullTextResult {
  id: string;
  created_at: number;
  updated_at: number;
  current: string;
  snippet: string;
}

/**
 * @returns Array of note metadata (id, timestamps)
 */
export async function listNotes(): Promise<NoteMeta[]> {
  return dbListNotes();
}

/**
 * Search across all active notes' content for the given query.
 * Snippets are extracted from the body (below frontmatter) when possible,
 * falling back to raw content when the match is only in the frontmatter.
 */
export async function fullTextSearch(query: string): Promise<FullTextResult[]> {
  const matches = await dbFullTextSearch(query);
  const q = query.toLowerCase();
  return matches.map(n => {
    const { body } = parseFrontmatter(n.content);
    const bodyIdx = body.toLowerCase().indexOf(q);

    let snippet: string;
    if (bodyIdx !== -1) {
      // Match in body — extract ~60 chars of context around the hit
      const start = Math.max(0, bodyIdx - 30);
      const end   = Math.min(body.length, bodyIdx + q.length + 30);
      snippet = body.slice(start, end);
      if (start > 0) snippet = '…' + snippet;
      if (end < body.length) snippet = snippet + '…';
    } else {
      // Match only in frontmatter — extract from raw content
      const idx   = n.content.toLowerCase().indexOf(q);
      const start = Math.max(0, idx - 30);
      const end   = Math.min(n.content.length, idx + q.length + 30);
      snippet = n.content.slice(start, end);
      if (start > 0) snippet = '…' + snippet;
      if (end < n.content.length) snippet = snippet + '…';
    }

    // Collapse whitespace for compact single-line display
    snippet = snippet.replace(/\s+/g, ' ');

    return {
      id:         n.id,
      created_at: n.created_at,
      updated_at: n.updated_at,
      current:    n.current,
      snippet,
    };
  });
}

/**
 * Load a note's content by id.
 * @returns NoteData with content, DB fields, and parsed frontmatter
 */
export async function loadNote(id: string): Promise<NoteData> {
  if (isSystemNote(id)) {
    const def = getSystemNote(id)!;
    const content = def.content();
    const now = Math.floor(Date.now() / 1000);
    const fm = parseFrontmatter(content);
    return {
      id, content,
      created_at: now, updated_at: now,
      current: 'system', created_by: 'leaf', updated_by: 'leaf',
      meta: fm.meta,
    };
  }
  const note = await dbGetNote(id);
  const content = note?.content ?? '';
  const fm = parseFrontmatter(content);
  return {
    id,
    content,
    created_at: note?.created_at ?? 0,
    updated_at: note?.updated_at ?? 0,
    current: note?.current ?? '',
    created_by: note?.created_by ?? '',
    updated_by: note?.updated_by ?? '',
    meta: fm.meta,
  };
}

/**
 * Save content to IndexedDB and queue an UPDATE for the server.
 */
export async function saveNote(id: string, content: string): Promise<{ ok: boolean }> {
  // Apply auto-tagging before the content comparison so that auto-tag
  // changes (including removals triggered by !*) are not lost.
  content = await applyAutotags(id, content);

  // Skip write + broadcast if content hasn't changed.
  const existing = await dbGetNote(id);
  if (existing && existing.content === content) return { ok: false };

  await dbSaveNote(id, content);
  publish({ type: 'saved', id });
  return { ok: true };
}

/**
 * Create a new note in IndexedDB and queue a CREATE for the server.
 */
export async function createNote(id: string): Promise<{ ok: boolean; file: string }> {
  await dbCreateNote(id);
  publish({ type: 'created', id });
  return { ok: true, file: id };
}

/**
 * Soft-delete in IndexedDB and queue a DELETE for the server.
 */
export async function deleteNote(id: string): Promise<{ ok: boolean }> {
  await dbDeleteNote(id);
  publish({ type: 'deleted', id });
  return { ok: true };
}

/**
 * Rename a note in IndexedDB and queue a RENAME for the server.
 */
export async function renameNote(oldId: string, newId: string): Promise<{ ok: boolean }> {
  await dbRenameNote(oldId, newId);
  publish({ type: 'renamed', id: oldId, newId });
  return { ok: true };
}
