/**
 * notes.ts — data access layer
 *
 * All reads/writes go to IndexedDB first.  The server is never called
 * directly from here.  Sync-queue entries are generated by sync.ts via
 * the change-bus, so notes.ts is purely persistence + publish.
 */

import {
  dbListNotes,
  dbGetNote,
  dbSaveNote,
  dbDeleteNote,
  dbCreateNote,
  dbRenameNote,
} from './db.js';
import type { NoteMeta } from './store.js';
import { parseFrontmatter } from './frontmatter.js';
import type { FrontmatterResult } from './frontmatter.js';
import { publish } from './change-bus.js';

/**
 * Full note data returned by loadNote().
 * Merges IndexedDB record fields with parsed frontmatter.
 */
export interface NoteData {
  id: string;           // note id (filename)
  content: string;      // full raw content (frontmatter + body)
  created_at: number;   // from IndexedDB record
  updated_at: number;   // from IndexedDB record
  current: string;      // from IndexedDB record
  created_by: string;   // from IndexedDB record (authoritative)
  updated_by: string;   // from IndexedDB record (authoritative)
  meta: FrontmatterResult['meta'];  // parsed frontmatter
}

/**
 * @returns Array of note metadata (id, timestamps)
 */
export async function listNotes(): Promise<NoteMeta[]> {
  return dbListNotes();
}

/**
 * Load a note's content by id.
 * @returns NoteData with content, DB fields, and parsed frontmatter
 */
export async function loadNote(id: string): Promise<NoteData> {
  const note = await dbGetNote(id);
  const content = note?.content ?? '';
  const fm = parseFrontmatter(content);
  return {
    id,
    content,
    created_at: note?.created_at ?? 0,
    updated_at: note?.updated_at ?? 0,
    current: note?.current ?? '',
    created_by: note?.created_by ?? '',
    updated_by: note?.updated_by ?? '',
    meta: fm.meta,
  };
}

/**
 * Save content to IndexedDB and queue an UPDATE for the server.
 */
export async function saveNote(id: string, content: string): Promise<{ ok: boolean }> {
  await dbSaveNote(id, content);
  publish({ type: 'saved', id });
  return { ok: true };
}

/**
 * Create a new note in IndexedDB and queue a CREATE for the server.
 */
export async function createNote(id: string): Promise<{ ok: boolean; file: string }> {
  await dbCreateNote(id);
  publish({ type: 'created', id });
  return { ok: true, file: id };
}

/**
 * Soft-delete in IndexedDB and queue a DELETE for the server.
 */
export async function deleteNote(id: string): Promise<{ ok: boolean }> {
  await dbDeleteNote(id);
  publish({ type: 'deleted', id });
  return { ok: true };
}

/**
 * Rename a note in IndexedDB and queue a RENAME for the server.
 */
export async function renameNote(oldId: string, newId: string): Promise<{ ok: boolean }> {
  await dbRenameNote(oldId, newId);
  publish({ type: 'renamed', id: oldId, newId });
  return { ok: true };
}
